#!/bin/bash
#
# setsas.sh - Automatically generated by configure_install at installation
# 
# SAS xmmsas_20210317_1624 - 19.1.0

platform=`uname -s`

if [ -z "$LHEASOFT" ] ; then 
  echo "setsas.sh: Error  - Please define and initialize HEASOFT! "
  return 1
fi

if [ -z "$SAS_PREV_PATH" ] ; then 
  SAS_PREV_PATH=$PATH                                ; export SAS_PREV_PATH
  if [ "$platform" = "Darwin" ] ; then
    SAS_PREV_DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH    ; export SAS_PREV_DYLD_LIBRARY_PATH
  else
    SAS_PREV_LD_LIBRARY_PATH=$LD_LIBRARY_PATH        ; export SAS_PREV_LD_LIBRARY_PATH
  fi
else
  PATH=$SAS_PREV_PATH                                ; export PATH
  if [ "$platform" = "Darwin" ] ; then 
    DYLD_LIBRARY_PATH=$SAS_PREV_DYLD_LIBRARY_PATH    ; export DYLD_LIBRARY_PATH
  else
    LD_LIBRARY_PATH=$SAS_PREV_LD_LIBRARY_PATH        ; export LD_LIBRARY_PATH
  fi  
fi

# Define SAS_DIR

SAS_DIR=/home/filippos/SASscreeningDR11              ; export SAS_DIR

# PYTHONPATH env variable required to run python based SAS tasks

if [ -z "$PYTHONPATH" ] ; then
	PYTHONPATH=$SAS_DIR/lib/python ; export PYTHONPATH
else
	PYTHONPATH=$SAS_DIR/lib/python:$PYTHONPATH ; export PYTHONPATH
fi

# Unset any previous definition of SAS_PATH (previous SAS initializations!)
unset SAS_PATH
. $SAS_DIR/sas-setup.sh
if [ "$platform" = "Darwin" ] ; then 
  ulimit -d unlimited
  ulimit -s 65532
fi

echo ; sasversion
echo ; echo "Do not forget to define SAS_CCFPATH, SAS_CCF and SAS_ODF"; echo
